/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#006c49",
        "on-primary": "#ffffff",
        "primary-container": "#10b981",
        "on-primary-container": "#00422b",
        "primary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#005236",
        "inverse-primary": "#4edea3",
        "surface-tint": "#006c49",

        "secondary": "#0051d5",
        "on-secondary": "#ffffff",
        "secondary-container": "#316bf3",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#003ea8",

        "tertiary": "#732ee4",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b48fff",
        "on-tertiary-container": "#4900a4",
        "tertiary-fixed": "#eaddff",
        "tertiary-fixed-dim": "#d2bbff",
        "on-tertiary-fixed": "#25005a",
        "on-tertiary-fixed-variant": "#5a00c6",

        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        "background": "#faf8ff",
        "on-background": "#131b2e",
        "surface": "#faf8ff",
        "surface-bright": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "surface-variant": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#3c4a42",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "outline": "#6c7a71",
        "outline-variant": "#bbcabf",

        quantix: {
          50: '#f0fdf4',
          100: '#dcfce7',
          500: '#10b981',
          600: '#006c49',
          900: '#00422b',
        }
      },
      borderRadius: {
        "DEFAULT": "0.75rem",
        "sm": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      spacing: {
        "pad-card-sm": "1rem",
        "touch-min": "3rem",
        "pad-terminal": "1.5rem",
        "touch-large": "4.5rem",
        "gap-standard": "1rem",
        "touch-standard": "3.5rem",
        "pad-card-lg": "1.75rem",
        "gap-compact": "0.5rem",
        "gap-spacious": "1.5rem",
        "gutter-split": "1.5rem"
      },
      fontFamily: {
        "label-numeric-lg": [ "Space Grotesk", "sans-serif" ],
        "display-lg": [ "Space Grotesk", "sans-serif" ],
        "headline-md": [ "Space Grotesk", "sans-serif" ],
        "title-md": [ "Geist", "sans-serif" ],
        "title-lg": [ "Space Grotesk", "sans-serif" ],
        "label-caps": [ "Space Grotesk", "sans-serif" ],
        "label-numeric-md": [ "Space Grotesk", "sans-serif" ],
        "body-lg": [ "Geist", "sans-serif" ],
        "display-lg-mobile": [ "Space Grotesk", "sans-serif" ],
        "headline-xl-mobile": [ "Space Grotesk", "sans-serif" ],
        "body-sm": [ "Geist", "sans-serif" ],
        "body-md": [ "Geist", "sans-serif" ],
        "headline-xl": [ "Space Grotesk", "sans-serif" ]
      },
      fontSize: {
        "label-numeric-lg": [ "32px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" } ],
        "display-lg": [ "48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" } ],
        "headline-md": [ "24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" } ],
        "title-md": [ "16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" } ],
        "title-lg": [ "20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" } ],
        "label-caps": [ "11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" } ],
        "label-numeric-md": [ "18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" } ],
        "body-lg": [ "16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" } ],
        "display-lg-mobile": [ "32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" } ],
        "headline-xl-mobile": [ "28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" } ],
        "body-sm": [ "12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" } ],
        "body-md": [ "14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" } ],
        "headline-xl": [ "36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" } ]
      }
    },
  },
  plugins: [],
}
