"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-08 22:53:03.556614
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('puntos_acumulados', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_telefono'), 'clientes', ['telefono'], unique=True)
    op.create_table('etl_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_disparo', sa.String(length=50), nullable=False),
    sa.Column('usuario_email', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duracion_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('origen_datos', sa.String(length=255), nullable=False),
    sa.Column('destino_archivo', sa.String(length=255), nullable=False),
    sa.Column('filas_bronze_ventas', sa.Integer(), nullable=False),
    sa.Column('filas_silver_ventas', sa.Integer(), nullable=False),
    sa.Column('filas_gold_ventas', sa.Integer(), nullable=False),
    sa.Column('filas_gold_productos', sa.Integer(), nullable=False),
    sa.Column('tamano_duckdb_kb', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('detalle_trazabilidad', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('contacto_nombre', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('lead_time_dias', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('CAJERO', 'BODEGUERO', 'SUPERVISOR', 'DIRECTOR', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('configuracion',
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo_dato', sa.String(length=20), nullable=False),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.Column('modificado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('auditoria_evento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('fecha_evento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gravedad', sa.String(length=50), nullable=False),
    sa.Column('venta_referencia_id', sa.UUID(), nullable=True),
    sa.Column('usuario_autorizador_id', sa.UUID(), nullable=True),
    sa.Column('ip_terminal', sa.String(length=45), nullable=True),
    sa.Column('detalle_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['usuario_autorizador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden_compra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.Column('usuario_solicitante_id', sa.UUID(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'RECIBIDA_PARCIAL', 'RECIBIDA', 'CANCELADA', name='estadoordencompra'), nullable=False),
    sa.Column('notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['usuario_solicitante_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('costo_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('margen_minimo_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requiere_pesaje', sa.Boolean(), nullable=False),
    sa.Column('clasificacion_abc', sa.String(length=1), nullable=True),
    sa.Column('imagen', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('sesion_caja',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('terminal_id', sa.String(length=255), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fondo_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTA', 'CERRADA', 'DESCUADRE', name='estadosesioncaja'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arqueo_caja',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sesion_caja_id', sa.UUID(), nullable=False),
    sa.Column('fecha_arqueo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_teorico', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_fisico_declarado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('diferencia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['sesion_caja_id'], ['sesion_caja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_orden_compra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orden_compra_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad_solicitada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_unitario_pactado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['orden_compra.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_inventario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('orden_compra_id', sa.UUID(), nullable=True),
    sa.Column('codigo_lote', sa.String(length=100), nullable=False),
    sa.Column('cantidad_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_disponible', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'AGOTADO', 'CADUCADO', 'MERMA', name='estadolote'), nullable=False),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['orden_compra.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regla_promocion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo_regla', sa.String(), nullable=False),
    sa.Column('producto_disparador_id', sa.UUID(), nullable=True),
    sa.Column('producto_beneficio_id', sa.UUID(), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('descuento_tipo', sa.String(), nullable=False),
    sa.Column('descuento_valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_minima', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_minimo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['producto_beneficio_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['producto_disparador_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sesion_caja_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('folio_ticket', sa.String(length=50), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('total_bruto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_impuestos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pagar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['sesion_caja_id'], ['sesion_caja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_folio_ticket'), 'ventas', ['folio_ticket'], unique=True)
    op.create_table('cupones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descuento_tipo', sa.String(), nullable=False),
    sa.Column('descuento_valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valido_desde', sa.Date(), nullable=False),
    sa.Column('valido_hasta', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('venta_canje_id', sa.Uuid(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['venta_canje_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cupones_codigo'), 'cupones', ['codigo'], unique=True)
    op.create_table('detalles_venta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('costo_unitario_lote', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margen_ganancia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_inventario.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_venta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('metodo_pago', sa.String(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referencia_pasarela', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos_venta')
    op.drop_table('detalles_venta')
    op.drop_index(op.f('ix_cupones_codigo'), table_name='cupones')
    op.drop_table('cupones')
    op.drop_index(op.f('ix_ventas_folio_ticket'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_table('regla_promocion')
    op.drop_table('lote_inventario')
    op.drop_table('detalle_orden_compra')
    op.drop_table('arqueo_caja')
    op.drop_table('sesion_caja')
    op.drop_table('producto')
    op.drop_table('orden_compra')
    op.drop_table('auditoria_evento')
    op.drop_table('configuracion')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('proveedor')
    op.drop_table('etl_log')
    op.drop_index(op.f('ix_clientes_telefono'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_table('categoria')
    op.execute('DROP TYPE IF EXISTS estadolote')
    op.execute('DROP TYPE IF EXISTS estadosesioncaja')
    op.execute('DROP TYPE IF EXISTS estadoordencompra')
    op.execute('DROP TYPE IF EXISTS rolusuario')
    # ### end Alembic commands ###
